export const bootLines = [
  ' _   _  ___  ___ ____ ',
  '| \\ | |/ _ \\|_ _|  _ \\',
  '|  \\| | | | || || |_) |',
  '| |\\  | |_| || ||  _ <',
  '|_| \\_|\\___/|___|_| \\_\\',
  '                           ',
  'Detective-OS BIOS v0.1.7',
  'Copyright (C) 1994-2025 Noir Systems',
  'CPU: Obsidian™ i7-1170G “Shadow Trace” @ 3.20GHz',
  'Memory Test: 32768MB OK',
  'Checking CMOS checksum . . . OK',
  'Initializing USB Controllers . . . Done',
  'Detecting PCI Devices . . . Done',
  'VGA BIOS . . . OK',
  'Detecting IDE Drives . . .',
  'Primary Master: Obsidian™ LM1000-1RK',
  'Primary Slave: None',
  'Secondary Master: None',
  'Secondary Slave: None',
  'Enabling SMART Monitoring . . . OK',
  'Boot Device: Evidence Vault (EV1)',
  'Loading boot sector . . . OK',
  'Loading boot loader . . . OK',
  'Unpacking kernel image . . . OK',
  'Loading Detective-OS . . . OK',
  'Initializing forensic subsystems . . .',
  'Checking evidence volumes . . . OK',
  'Mounting / . . . OK',
  'Mounting /mnt . . . OK',
  'Mounting /home . . . OK',
  'Starting device manager . . . OK',
  'Starting input services . . . OK',
  'Starting audio services . . . OK',
  'Starting noir-shell . . . OK',
  'Launching welcome screen . . .'
]
