export const bootLines = [
  'Detective-OS BIOS v0.1.7',
  'Copyright (C) 1994-2025 Noir Systems',
  'CPU: Intel(R) Core(TM) i7-1165G7 @ 2.80GHz',
  'Memory Test: 32768MB OK',
  'Checking CMOS checksum . . . OK',
  'Initializing USB Controllers . . . Done',
  'Detecting PCI Devices . . . Done',
  'VGA BIOS . . . OK',
  'Detecting IDE Drives . . .',
  'Primary Master: ST1000LM035-1RK172',
  'Primary Slave: None',
  'Secondary Master: None',
  'Secondary Slave: None',
  'Enabling SMART Monitoring . . . OK',
  'Boot Device: Evidence Vault (EV1)',
  'Loading boot sector . . . OK',
  'Loading boot loader . . . OK',
  'Unpacking kernel image . . . OK',
  'Loading Detective-OS . . . OK',
  'Initializing forensic subsystems . . .',
  'Checking evidence volumes . . . OK',
  'Mounting /mnt/evidence . . . OK',
  'Mounting /mnt/locker . . . OK',
  'Starting device manager . . . OK',
  'Starting input services . . . OK',
  'Starting audio services . . . OK',
  'Starting noir-shell . . . OK',
  'Launching welcome screen . . .'
]
